Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from Tools import *
  File "/data/scratch/rhklein/RL-Python/Tools.py", line 18, in <module>
    if module_exists('matplotlib'):
  File "/data/scratch/rhklein/RL-Python/Tools.py", line 6, in module_exists
    __import__(module_name)
  File "/usr/lib/pymodules/python2.7/matplotlib/__init__.py", line 774, in <module>
    rcParams = rc_params()
  File "/usr/lib/pymodules/python2.7/matplotlib/__init__.py", line 692, in rc_params
    fname = matplotlib_fname()
  File "/usr/lib/pymodules/python2.7/matplotlib/__init__.py", line 604, in matplotlib_fname
    fname = os.path.join(get_configdir(), 'matplotlibrc')
  File "/usr/lib/pymodules/python2.7/matplotlib/__init__.py", line 253, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/__init__.py", line 480, in _get_configdir
    os.mkdir(p)
OSError: [Errno 17] File exists: '/tmp/.matplotlib'
